### ISSUE TITLE
GPU memory leakage when creating objects from sentence-transformers

### ISSUE THREAD

**Issue by ldbolanos** [rstudio/reticulate#798]
# **Description**
I am creating a function in R that embeds sentences using the `sentence_transformers` library from Python. 

For some unknown reason, creating the object multiple times under the same variable name ends up in insufficient memory space to allocate the transformer. To reproduce:

```{r}
sentence_transformers <- reticulate::import("sentence_transformers")
for (i in 1:10) {
  print(i)
  bert_encoder <- sentence_transformers$SentenceTransformer("bert-large-nli-stsb-mean-tokens")
}
```
However, doing the same operation directly on Python does not produce an error
```{Python}
from sentence_transformers import SentenceTransformer
for i in range(10):
    print(i)
    bert_encoder = SentenceTransformer("bert-large-nli-stsb-mean-tokens")
}
```
This happens with any model that is allocated in GPU. On my NVIDIA GTX 1060 it reaches the 4th cycle, but on smaller GPUs it crashes earlier. One temporal solution is to create the model outside only once, and then pass the model as a parameter to the function as many times as wanted, but I would rather avoid that because it adds an extra step and in any case calling multiple models might just make it crash as well.

# **Expected behaviour**
The for loop finishes without an error

# **Observed behaviour**
_Error in py_call_impl(callable, dots$args, dots$keywords) : 
  RuntimeError: CUDA out of memory. Tried to allocate 20.00 MiB (GPU 0; 6.00 GiB total capacity; 2.95 GiB already allocated; 16.11 MiB free; 238.68 MiB cached)_ 

# **Unsuccesful attemps at solving it**

1. The solutions proposed [here](https://github.com/tensorflow/tensorflow/issues/36465)
2. Using numba as suggested [here](https://stackoverflow.com/a/60354785/5559413)
3. Declaring the variable explicitely on Python via `reticulate::py_run_string()` and then doing `del bert_encoder` and calling the garbage collector

# **Details**
Windows 10 Home
Python 3.7.4
R 4.0.1
Reticulate 1.16
Torch 1.3.1
Tensorflow 2.2.0
Transformers 2.11.0
sentence_transformers 0.2.6

**Comment by skeydan** [comment]
Unfortunately I can reproduce...

```
sentence_transformers <- reticulate::import("sentence_transformers")
for (i in 1:10) {
  system("nvidia-smi | grep MiB | grep Default")
  bert_encoder <- sentence_transformers$SentenceTransformer("bert-large-nli-stsb-mean-tokens")
}

| N/A   42C    P0    N/A /  N/A |   1060MiB /  4035MiB |      1%      Default |
| N/A   43C    P0    N/A /  N/A |   2760MiB /  4035MiB |     65%      Default |
| N/A   44C    P0    N/A /  N/A |   4034MiB /  4035MiB |     21%      Default |
Error in py_call_impl(callable, dots$args, dots$keywords) : 
RuntimeError: CUDA out of memory. Tried to allocate 120.00 MiB (GPU 0; 3.94 GiB total capacity; 2.50 GiB already allocated; 1.56 MiB free; 2.50 GiB reserved in total by PyTorch) 
```

vs

```
> reticulate::repl_python()
Python 3.8.3 (/home/key/.virtualenvs/torch/bin/python3)
Reticulate 1.16 REPL -- A Python interpreter in R.
>>> import os
>>> from sentence_transformers import SentenceTransformer
>>> for i in range(10):
...     os.system("nvidia-smi | grep MiB | grep Default")
...     bert_encoder = SentenceTransformer("bert-large-nli-stsb-mean-tokens")
... 
| N/A   43C    P0    N/A /  N/A |   1053MiB /  4035MiB |      0%      Default |
| N/A   44C    P0    N/A /  N/A |   2753MiB /  4035MiB |     63%      Default |
| N/A   44C    P0    N/A /  N/A |   4027MiB /  4035MiB |     64%      Default |
| N/A   44C    P0    N/A /  N/A |   4027MiB /  4035MiB |     52%      Default |
| N/A   45C    P0    N/A /  N/A |   4027MiB /  4035MiB |     60%      Default |
| N/A   45C    P0    N/A /  N/A |   4027MiB /  4035MiB |     53%      Default |
| N/A   45C    P0    N/A /  N/A |   4027MiB /  4035MiB |      5%      Default |
| N/A   45C    P0    N/A /  N/A |   4027MiB /  4035MiB |     85%      Default |
| N/A   45C    P0    N/A /  N/A |   4027MiB /  4035MiB |     83%      Default |
| N/A   46C    P0    N/A /  N/A |   4027MiB /  4035MiB |     74%      Default |
```

Unfortunately I do not know it there's a workaround apart from the one you already mention.
@dfalbel would probably know?

**Comment by ldbolanos** [comment]
@skeydan Thank you for your reply.

I found an ugly workaround, but is in fact a workaround and not a fix. Starting from the 3rd unsuccesful attempt to solve the issue (as mentioned in the OP)

> Declaring the variable explicitely on Python via `reticulate::py_run_string()` and then doing `del bert_encoder` and calling the garbage collector

I included the removal of the R variable. This leads to

```
# Helper function
get_used_memory <- function() {
  py <- reticulate::py_run_string("import torch
used_memory = torch.cuda.memory_allocated('cuda')")
  return(py$used_memory)
}

# Calling the model
py <- reticulate::py_run_string("from sentence_transformers import SentenceTransformer
encoder = SentenceTransformer(\"bert-large-nli-stsb-mean-tokens\")")
encoder <- reticulate::py$encoder

# Waiting for release
while(get_used_memory() > 0) {

        #Delete the Python object
        tryCatch(reticulate::py_run_string("del encoder"),
                 warning = function(e) {},
                 error = function(e) {})

        #Delete R objects
        tryCatch(rm(encoder),
                 warning = function(e) {},
                 error = function(e) {})

        rm(py)

        # Garbage collector
        gc <- reticulate::import("gc")
        gc$collect()

        # Release PyTorch
        py <- reticulate::py_run_string("import torch
torch.cuda.empty_cache()")
      }
```
which seems to work. 

I observed that running the above piece of code once **does not always** releases the GPU, and so I had to wrap everything inside a while in order to wait for the magic to happen. 

The tryCatch statements exist because after the first iteration there are no more objects.

Sometimes, it takes 2 iterations to release memory, sometimes 20. I can not find the underlying pattern.

**Comment by dfalbel** [comment]
Calling `gc(full = TRUE)` seems to fix for me:

```
> sentence_transformers <- reticulate::import("sentence_transformers")
2020-07-17 11:56:59.753659: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libnvinfer.so.6'; dlerror: libnvinfer.so.6: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/lib/R/lib::/lib:/usr/lib/x86_64-linux-gnu:/usr/lib/jvm/default-java/lib/server
2020-07-17 11:56:59.753757: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libnvinfer_plugin.so.6'; dlerror: libnvinfer_plugin.so.6: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/lib/R/lib::/lib:/usr/lib/x86_64-linux-gnu:/usr/lib/jvm/default-java/lib/server
2020-07-17 11:56:59.753763: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:30] Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
> SentenceTransformer <- sentence_transformers$SentenceTransformer
> 
> for (i in 1:10) {
+   gc(full = TRUE)
+   system("nvidia-smi | grep MiB | grep Default")
+   bert_encoder <- SentenceTransformer("bert-large-nli-stsb-mean-tokens")
+   
+ }
| 27%   44C    P2    87W / 270W |    393MiB / 11175MiB |      0%      Default |
| 27%   45C    P2    87W / 270W |   2244MiB / 11175MiB |     56%      Default |
| 27%   45C    P2    87W / 270W |   3518MiB / 11175MiB |     14%      Default |
| 27%   45C    P2    87W / 270W |   3518MiB / 11175MiB |      2%      Default |
| 27%   45C    P2    87W / 270W |   3518MiB / 11175MiB |      6%      Default |
| 27%   44C    P2    70W / 270W |   3518MiB / 11175MiB |     31%      Default |
| 27%   44C    P2    79W / 270W |   3518MiB / 11175MiB |     53%      Default |
| 27%   45C    P2    87W / 270W |   3518MiB / 11175MiB |     67%      Default |
| 27%   45C    P2    87W / 270W |   3518MiB / 11175MiB |     62%      Default |
| 27%   46C    P2    87W / 270W |   3518MiB / 11175MiB |     34%      Default |
```

**Comment by ldbolanos** [comment]
Doing 
```
gc(full = TRUE)
py <- reticulate::py_run_string("import torch
torch.cuda.empty_cache()")
```

works for me. Simpler and nicer. Thank you so much!

> I think R is not smart enough to release the bert_encoder because it doesn't seem to R that it takes so much memory...

I did the same test with BERT from the `transformers` library and this does not happen though. Weird

**Comment by skeydan** [comment]
thanks for finding a solution @dfalbel ! I'm just surprised at

```
2020-07-17 11:56:59.753659: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libnvinfer.so.6'; dlerror: libnvinfer.so.6: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/lib/R/lib::/lib:/usr/lib/x86_64-linux-gnu:/usr/lib/jvm/default-java/lib/server
```
etc...

... I had run `pip install sentence_transformers` iin my Pytorch env to reproduce this ....
